// src/components/shared/Header/Header.tsx
import Link from "next/link";
import React from "react";

const Header = () => {
  return (
    <header className={`w-full fixed top-0 left-0 z-10 px-5 xl:px-0 bg-white`}>
      <div className="w-full layout flex items-center justify-between h-[60px] ">
        <Link className="text-xl font-semibold" href="/">
          workmeetcoffee.
        </Link>
        <nav>
          <ol className="flex gap-[16px]">
            <li>
              <Link href="/contribute">contribute</Link>
            </li>
          </ol>
        </nav>
      </div>
    </header>
  );
};

export default Header;

// src/components/Header.svelte
<header class="w-full bg-base2 px-5 lg:px-0 py-6 sticky top-0 left-0 right-0">
  <div class="flex justify-between wmc-container items-center">
    <a href="/" class="text-xl font-semibold">
      Work Meet Coffee
    </a>
    <nav>
      <ul class="flex flex-row gap-3">
        <a href="/coffee-shop">
          <li>Coffee Shop</li>
        </a>
        <a href="/submission">
          <li>Submission</li>
        </a>
      </ul>
    </nav>
  </div>
</header>
