// src/components/Header/Header.tsx
"use client";

import Link from "next/link";
import React from "react";

const Header = () => {
  return (
    <header className="w-full sticky top-0 z-50 bg-white">
      <nav className="layout flex justify-between py-4 px-4 lg:px-0">
        <Link href="/" className="text-lg font-medium">
          workmeetcoffee
        </Link>
        <div>
          <Link href="/contribute">contribute</Link>
        </div>
      </nav>
    </header>
  );
};

export default Header;

// src/components/Header.svelte
<header class="w-full bg-base2 px-5 lg:px-0 py-6 sticky top-0 left-0 right-0">
  <div class="flex justify-between wmc-container items-center">
    <a href="/" class="text-xl font-semibold">
      Work Meet Coffee
    </a>
    <nav>
      <ul class="flex flex-row gap-3">
        <a href="/coffee-shop">
          <li>Coffee Shop</li>
        </a>
        <a href="/submission">
          <li>Submission</li>
        </a>
      </ul>
    </nav>
  </div>
</header>
